
# Basic
name:               "ZJun"



author:
  name:             Jun Zhang
  facebook:         your-id
  twitter:          your-id
  github:           https://github.com/ZJCODE
  linkedin:         https://cn.linkedin.com/in/俊-张-a0459ba7
  medium:           your-id
  tumblr:           your-id
  email:            zhangjun310@live.com

# Google-analytics
google-analytics:
  id:               ""

# Disqus
disqus:
  id:               "your-id"

# URL
url:                "https://zjcode.github.io"
#url:               "localhost:4000"
baseurl:            ""


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Asia/China
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           20
paginate_path:      /page:num/

# Build settings
markdown:           kramdown

# Navigation
nav:
  - name:           "About"
    url:            "/about"
  - name:           "Archive"
    url:            "/archive"
  - name:           "Tags"
    url:            "/tags"
  - name:           "Github"
    url:            "https://github.com/ZJCODE"



# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate

exclude:            [vendor]
